version: '3.1'
services: 

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  frontend:
    ports: 
      - "8080:8080"
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - api

  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: calendardb

